### GET request all metrics
GET http://localhost:8080
Accept: text/html

### GET request value counter
GET http://localhost:8081/value/counter/PollCount
Accept: application/json

### GET request value gauge
GET http://localhost:8080/value/gauge/HeapInuse
Accept: application/json

### Send POST Update Gauge Metric
POST http://localhost:8080/update/gauge/RandomValue/2
Content-Type: text/html

### Send POST Update Counter Metric
POST http://localhost:8080/update/counter/PollCount/2
Content-Type: text/html


### Send POST Update Counter Metric with json body
POST http://localhost:8080/update/
Content-Type: application/json

{
  "type":"counter",
  "id":"PollCount1",
  "delta":2
}

### Send POST Get Counter Metric with json body
POST http://localhost:8080/value/
Content-Type: application/json
Accept-Encoding: gzip

    {
      "type": "counter",
      "id": "PollCount1"
    }


### Send POST Update Gauge Metric with json body
POST http://localhost:8080/update/
Content-Type: application/json

{
  "type":"gauge",
  "id":"Alloc1",
  "value":2
}

### Send POST Get Gauge Metric with json body
POST http://localhost:8080/value/
Content-Type: application/json

{
  "type":"gauge",
  "id":"Alloc1"
}

### Send POST Update batch with json body
POST http://localhost:8080/updates/
Content-Type: application/json

[
  {
    "type": "counter",
    "id": "PollCount1",
    "delta": 1
  },
  {
    "type": "counter",
    "id": "PollCount2",
    "delta": 2
  },
  {
    "type": "counter",
    "id": "PollCount3",
    "delta": 2
  },
  {
    "type": "counter",
    "id": "PollCount4",
    "delta": 2
  }
]

### gRPC Unary Call
GRPC localhost:3200/value/counter/PollCount
Content-Type: application/grpc



### gRPC Stream Call (если сервис поддерживает стриминг)
GRPC localhost:3200/metrics.Metrics/GetAllMetrics
Content-Type: application/grpc

{}

### Get all metrics
GRPC localhost:3200/metrics.Metrics/GetAllMetrics
Content-Type: application/grpc

### Get single metric
GRPC localhost:3200/metrics.Metrics/GetMetric
Content-Type: application/grpc

{
  "type": "counter",
  "name": "PollCount1"
}

### Update single metric
GRPC localhost:3200/metrics.Metrics/UpdateMetric
Content-Type: application/grpc

{
  "metric": {
    "id": "PollCount1",
    "type": "counter",
    "delta": 2,
    "value": 0
  }
}

### Update multiple metrics
GRPC localhost:3200/metrics.Metrics/UpdateMetrics
Content-Type: application/grpc

{
  "metrics": [
    {
      "id": "HeapInuse",
      "type": "gauge",
      "value": 123.45
    },
    {
      "id": "PollCount",
      "type": "counter",
      "delta": 10
    }
  ]
}






