### GET request all metrics
GET http://localhost:8080
Accept: text/html

### GET request value counter
GET http://localhost:8080/value/counter/PollCount
Accept: application/json

### GET request value gauge
GET http://localhost:8080/value/gauge/HeapInuse
Accept: application/json

### Send POST Update Gauge Metric
POST http://localhost:8080/update/gauge/RandomValue/2
Content-Type: text/html

### Send POST Update Counter Metric
POST http://localhost:8080/update/counter/PollCount/2
Content-Type: text/html


### Send POST Update Counter Metric with json body
POST http://localhost:8080/update/
Content-Type: application/json

{
  "type":"counter",
  "id":"PollCount1",
  "delta":2
}

### Send POST Get Counter Metric with json body
POST http://localhost:8080/value/
Content-Type: application/json
Accept-Encoding: gzip

    {
      "type": "counter",
      "id": "PollCount1"
    }


### Send POST Update Gauge Metric with json body
POST http://localhost:8080/update/
Content-Type: application/json

{
  "type":"gauge",
  "id":"Alloc1",
  "value":2
}

### Send POST Get Gauge Metric with json body
POST http://localhost:8080/value/
Content-Type: application/json

{
  "type":"gauge",
  "id":"Alloc1"
}

### Send POST Update batch with json body
POST http://localhost:8080/updates/
Content-Type: application/json

[
  {
    "type": "counter",
    "id": "PollCount1",
    "delta": 1
  },
  {
    "type": "counter",
    "id": "PollCount2",
    "delta": 2
  },
  {
    "type": "counter",
    "id": "PollCount3",
    "delta": 2
  },
  {
    "type": "counter",
    "id": "PollCount4",
    "delta": 2
  }
]





